### ISSUE TITLE
[dev-util/clion-2016.2] Incorrect permissions

### ISSUE THREAD

**Issue by ShyPixie** [samuelbernardo/ssnb-overlay#1]
Some incorrect permissions in the files is causing exceptions.

These files must be executables:

/opt/clion-2016.2.1/bin/lldb/LLDBFrontend 
/opt/clion-2016.2.1/bin/lldb/bin/lldb-server
/opt/clion-2016.2.1/bin/lldb/lib/python2.7/site-packages/lldb/lldb-argdumper

**Comment by samuelbernardo** [comment]
Thanks for your feedback and sorry for my answer delay.
I'll correct that this weekend.

**Comment by samuelbernardo** [comment]
Missing file permissions corrected.
There is a newer version available from official gentoo portage (clion-2016.2.1).
I haven't tested it yet, but since is keyword masked in portage and the file permissions correction seems smaller, maybe it needs some additional review.
