### ISSUE TITLE
megasync ffmpeg patch is missing

### ISSUE THREAD

**Issue by CapSel** [samuelbernardo/ssnb-overlay#10]
```
# emerge megasync
Calculating dependencies... done!

>>> Verifying ebuild manifests

!!! A file listed in the Manifest could not be found: /var/db/repos/ssnb/net-misc/megasync/files/megasync-3.6.5-ffmeg.patch
```

**Comment by CapSel** [comment]
Solved it by manually updating manifest:
`ebuild /var/db/repos/ssnb/net-misc/megasync/megasync-3.6.6.ebuild manifest`

**Comment by samuelbernardo** [comment]
Hi @CapSel ,
Sorry for the delay in my answer.
Thanks for your feedback.
Because I'm using a local overlay before I publish to my ssnb overlay I missed that patch file.
I've in my todo list install a CI for ssnb that will help to review such errors with a clean profile.
Cheers
